-- div-environments.lua
-- Maps Quarto fenced divs with custom classes to LaTeX environments.
-- Only active for LaTeX/PDF output.

-- ============================================================================
-- Page numbering: inject \pagenumbering{arabic} at document body start
-- (after TOC, which is generated by the LaTeX template, not in the AST).
-- ============================================================================

local page_numbering_injected = false

function Pandoc(doc)
  if FORMAT:match("latex") or FORMAT:match("pdf") then
    local raw = pandoc.RawBlock("latex", "\\pagenumbering{arabic}\\pagestyle{fancy}")
    table.insert(doc.blocks, 1, raw)
  end
  return doc
end

local env_map = {
  introduction = true,
  example      = true,
  exercise     = true,
  problem      = true,
  note         = true,
  assumption   = true,
  conclusion   = true,
  property     = true,
  problemset   = true,
  proof        = true,
  solution     = true,
  remark       = true,
}

function Div(el)
  -- Only process for LaTeX/PDF output
  if not FORMAT:match("latex") and not FORMAT:match("pdf") then
    return nil
  end

  -- Inject \pagestyle{plain} before the #refs div (bibliography)
  -- to suppress page headers on bibliography pages.
  if el.identifier == "refs" then
    local pagestyle = pandoc.RawBlock("latex", "\\pagestyle{plain}")
    -- Keep the original div for Quarto's CSL processing
    return { pagestyle, el }
  end

  -- Look for a class matching one of our environments
  for _, cls in ipairs(el.classes) do
    if env_map[cls] then
      local begin_block = pandoc.RawBlock("latex", "\\begin{" .. cls .. "}")
      local end_block   = pandoc.RawBlock("latex", "\\end{" .. cls .. "}")
      local blocks = {}
      table.insert(blocks, begin_block)
      for _, b in ipairs(el.content) do
        table.insert(blocks, b)
      end
      table.insert(blocks, end_block)
      return blocks
    end
  end
  return nil
end

-- ============================================================================
-- Equation numbering: convert standalone DisplayMath ($$...$$) blocks
-- into numbered equation environments (\begin{equation}...\end{equation}).
-- ============================================================================

local function is_standalone_display_math(block)
  if (block.t == "Plain" or block.t == "Para") and #block.content == 1 then
    local elem = block.content[1]
    if elem.t == "Math" and elem.mathtype == "DisplayMath" then
      return elem.text
    end
  end
  return nil
end

function Plain(el)
  if not (FORMAT:match("latex") or FORMAT:match("pdf")) then
    return nil
  end
  local math_text = is_standalone_display_math(el)
  if math_text then
    -- Strip any embedded newlines to keep LaTeX equation on one logical line
    math_text = math_text:gsub("\n", " ")
    return pandoc.RawBlock("latex", "\\begin{equation}" .. math_text .. "\\end{equation}")
  end
  return nil
end

function Para(el)
  if not (FORMAT:match("latex") or FORMAT:match("pdf")) then
    return nil
  end
  local math_text = is_standalone_display_math(el)
  if math_text then
    -- Strip any embedded newlines to keep LaTeX equation on one logical line
    math_text = math_text:gsub("\n", " ")
    return pandoc.RawBlock("latex", "\\begin{equation}" .. math_text .. "\\end{equation}")
  end
  return nil
end
